### ISSUE TITLE
ColdBox error on start

### ISSUE THREAD

**Issue by bockensm** [LearnCF/CFMLChallenge-app#1]
It looks like the embedded `cfml-challenge` app tries to run tests on port 51741 but the server is not configured to start on that port.

Steps:
1. Cloned repo
1. `box install`
1. `box server start`

**Comment by bockensm** [comment]
There are really two options to solve this:

1) Update `server.json` in this repository and hard-code the port. Hardcoding ports might result in a conflict for someone in some case.

2) Update the `cfmlchallenge` module to pass whatever port is being used through to the test runner. This is the better option, in my opinion.

Since option 2 seems appropriate, the issue in the scope of this project is irrelevant, and I will close the issue.

**Comment by michaelborn** [comment]
Thanks @bockensm ! I'll get a fix pushed up to the challenge module.
